dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install pytest
  - pip install pytest-flake8
  - git clone https://github.com/szabgab/slider-py.git
  - pip install -r slider-py/requirements.txt
script:
  - python tests/check.py
  - python generate_slides.py
